const fs = require('fs');

const message = `
// ------------------------------------------------------- //
// Autogenerated, do not edit. All changes will be undone. //
// ------------------------------------------------------- //

`;

function apply(options, compiler) {
}

/**
 * Export the plugin function
 */
module.exports = function(filepath) {
  fs.writeFileSync(filepath, message, 'utf8');
  return {
    apply: apply.bind(this, filepath),
  };
};
